// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD6XC5FNEqeIXv-Veif-OzP5Hy2uZrXTU',
    appId: '1:648895799301:web:012fc31d3f37c756d1fc6c',
    messagingSenderId: '648895799301',
    projectId: 'example-f5ba9',
    authDomain: 'example-f5ba9.firebaseapp.com',
    databaseURL: 'https://example-f5ba9-default-rtdb.firebaseio.com',
    storageBucket: 'example-f5ba9.firebasestorage.app',
    measurementId: 'G-ZTHCVJRL07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALnxrG1nW2snhx2h8tH-21QMnfHQFVFV8',
    appId: '1:648895799301:android:6376bac615bebe2ed1fc6c',
    messagingSenderId: '648895799301',
    projectId: 'example-f5ba9',
    databaseURL: 'https://example-f5ba9-default-rtdb.firebaseio.com',
    storageBucket: 'example-f5ba9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaUKDh3hvxhlTxyLQcdnYcxzeVgCkN_ow',
    appId: '1:648895799301:ios:ec48cbc005f1f8b0d1fc6c',
    messagingSenderId: '648895799301',
    projectId: 'example-f5ba9',
    databaseURL: 'https://example-f5ba9-default-rtdb.firebaseio.com',
    storageBucket: 'example-f5ba9.firebasestorage.app',
    iosBundleId: 'com.example.dddd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaUKDh3hvxhlTxyLQcdnYcxzeVgCkN_ow',
    appId: '1:648895799301:ios:ec48cbc005f1f8b0d1fc6c',
    messagingSenderId: '648895799301',
    projectId: 'example-f5ba9',
    databaseURL: 'https://example-f5ba9-default-rtdb.firebaseio.com',
    storageBucket: 'example-f5ba9.firebasestorage.app',
    iosBundleId: 'com.example.dddd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD6XC5FNEqeIXv-Veif-OzP5Hy2uZrXTU',
    appId: '1:648895799301:web:b589520fc9ca14c9d1fc6c',
    messagingSenderId: '648895799301',
    projectId: 'example-f5ba9',
    authDomain: 'example-f5ba9.firebaseapp.com',
    databaseURL: 'https://example-f5ba9-default-rtdb.firebaseio.com',
    storageBucket: 'example-f5ba9.firebasestorage.app',
    measurementId: 'G-30VPXQJ0EY',
  );
}
